# Generated by Django 3.1.1 on 2020-10-18 15:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('place', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityTour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('places', models.ManyToManyField(blank=True, null=True, related_name='places_cityTours', to='place.Place')),
                ('users', models.ManyToManyField(blank=True, null=True, related_name='users_cityTours', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
