# Generated by Django 3.1.1 on 2020-11-08 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cityTour", "0004_auto_20201107_1239"),
    ]

    operations = [
        migrations.AddField(
            model_name="citytour",
            name="continent",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="citytour",
            name="country",
            field=models.CharField(default="", max_length=255),
        ),
    ]
