# Generated by Django 3.1.1 on 2020-11-29 15:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cityTour", "0006_auto_20201119_1122"),
    ]

    operations = [
        migrations.AlterField(
            model_name="citytour",
            name="date",
            field=models.DateField(default=datetime.date(2020, 11, 29)),
        ),
    ]
