# Generated by Django 3.1.1 on 2020-11-29 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cityTour", "0008_citytourtemplate"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="citytourtemplate",
            name="date",
        ),
    ]
