# Generated by Django 3.1.1 on 2020-11-29 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("place", "0007_auto_20201129_1624"),
        ("cityTour", "0009_remove_citytourtemplate_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="citytourtemplate",
            name="places",
            field=models.ManyToManyField(
                blank=True, related_name="places_cityToursTemplates", to="place.Place"
            ),
        ),
    ]
