# Generated by Django 3.1.1 on 2020-10-18 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xid', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('point', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
    ]
