# Generated by Django 3.1.1 on 2020-11-07 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("place", "0003_remove_place_order"),
    ]

    operations = [
        migrations.RenameField(
            model_name="place",
            old_name="xid",
            new_name="idx",
        ),
    ]
