# Generated by Django 3.1.1 on 2020-11-07 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("place", "0004_auto_20201107_1829"),
    ]

    operations = [
        migrations.RenameField(
            model_name="place",
            old_name="idx",
            new_name="xid",
        ),
    ]
