# Generated by Django 3.1.1 on 2020-11-29 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("place", "0005_auto_20201107_1832"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="place",
            name="distance",
        ),
        migrations.RemoveField(
            model_name="place",
            name="duration",
        ),
    ]
